### ISSUE TITLE
Extream in game lag

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#1]
This is caused by rendering images over and over in the draw methods

- Fix the images rendering multiple times(Wall class)

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
!assign  @aniruddhajoshi100  60

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 60

**Comment by adityatr64** [comment]
! assign @aniruddhajoshi100 60

**Comment by SuchitraShankar07** [comment]
!assign @aniruddhajoshi100 60

**Comment by adityatr64** [comment]
You have been assigned elsewhere please finish the issue there and then ask 🙂

**Comment by aniruddhajoshi100** [comment]
can I get this assigned now ?

**Comment by SuchitraShankar07** [comment]
!assign @aniruddhajoshi100 35

**Comment by AnshulBanda** [comment]
can i get this assigned to me?

**Comment by adityatr64** [comment]
!assign @AnshulBanda 75

**Comment by Keeru-2005** [comment]
can i get assigned this issue @adityatr64

**Comment by adityatr64** [comment]
> can i get assigned this issue @adityatr64

Im sorry but this issue was closed a few mins ago
