### ISSUE TITLE
Move to sprites

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#2]
The game currently uses rects for drawing the objects on screen

- Use pygame sprites instead 
- make sure the game lag is reduced not increased in the process

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
seems like you have been assigned else where please complete that assignment and return here

**Comment by Tarun600GK** [comment]
can i get assigned ?

**Comment by codespiderr** [comment]
can I get assigned to this?

**Comment by adityatr64** [comment]
!assign @codespiderr 90

**Comment by codespiderr** [comment]
can I deassign from this?

**Comment by adityatr64** [comment]
!deassign

**Comment by sujith27pes** [comment]
can i work on this @sujith27pes

**Comment by sujith27pes** [comment]
!assign @sujith27pes

**Comment by adityatr64** [comment]
!assign @sujith27pes 60

**Comment by PerepaMoorty** [comment]
I could take on this Assignment!
Could you please assign me to this issue

**Comment by adityatr64** [comment]
> I could take on this Assignment! Could you please assign me to this issue

There is PR under review so this most prolly a solved issue

**Comment by PerepaMoorty** [comment]
I see

**Comment by PerepaMoorty** [comment]
Has this issue been solved?
Or are there possibilites for another assignment?

**Comment by adityatr64** [comment]
> Has this issue been solved? Or are there possibilites for another assignment?

cannot say still recording the issues

**Comment by anirudh-os** [comment]
@adityatr64 Can i work on this ?

**Comment by sujith27pes** [comment]
I am working on the changes and i am almost done

**Comment by anirudh-os** [comment]
Ok

**Comment by sujith27pes** [comment]
can i be assigned to this?

**Comment by sujith27pes** [comment]
I am working on the changes and have to commit them

**Comment by adityatr64** [comment]
!assign @sujith27pes 60

**Comment by stealthwhizz** [comment]
@adityatr64 assign me

**Comment by adityatr64** [comment]
> @adityatr64 assign me

This will be closed since it was fixed to a acceptable level

**Comment by adityatr64** [comment]
!deassign
