### ISSUE TITLE
Menu GUI Enhancements

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#3]
The current game menu is made using tkinter 

- needs a rework on the gui part
- The menu also creates a new window and/or needs hide the menu window

**Comment by himaniraoo** [comment]
can i please be assigned @adityatr64

**Comment by adityatr64** [comment]
!assign @himaniraoo 60

**Comment by RisuKumari11** [comment]
can i be assigned this

**Comment by adityatr64** [comment]
> can i be assigned this
This issues has already been assigned to someone else

**Comment by himaniraoo** [comment]
@adityatr64 , i've worked on the gui but i'm having troubles cloning it via git , i had copy pasted code form main.py to work on it , could u pls let me know what to do

**Comment by himaniraoo** [comment]
@adityatr64 , i have modified the menu.py in the repository

**Comment by adityatr64** [comment]
@himaniraoo do make a pr for review

**Comment by himaniraoo** [comment]
@adityatr64 , i have pulled a request

**Comment by himaniraoo** [comment]
@adityatr64 , can you please reassign , im working on it

**Comment by adityatr64** [comment]
!deassign

**Comment by himaniraoo** [comment]
@adityatr64 , i have pulled a request , kindly check pls :')

**Comment by adityatr64** [comment]
!assign @himaniraoo 30

**Comment by himaniraoo** [comment]
@adityatr64 , sorry i had not received your previous message , i updated menu.py rn and i will be pulling a request , kindly ignore the second one

**Comment by PerepaMoorty** [comment]
Hello There, This issue is something I could work on
Could I have this assignment? @adityatr64

**Comment by adityatr64** [comment]
!assign @PerepaMoorty 60

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @PerepaMoorty 60

**Comment by mahika34** [comment]
can i be assigned

**Comment by PerepaMoorty** [comment]
Could you further elaborate on what parts of the GUI need to be worked on or rather how you would want it to look like

**Comment by adityatr64** [comment]
> Could you further elaborate on what parts of the GUI need to be worked on or rather how you would want it to look like

As you can see the thge backgroung image is very bare bones Choose/make a image that suits the theme of the game
and some changes in the tkinter interface to make it look good with whatever image you've selected

**Comment by adityatr64** [comment]
> can i be assigned

This issue was already assigned to someone else 
you can try if they give up

**Comment by PerepaMoorty** [comment]
I have made some progress on the UI and also made so that the Menu Window is hidden
Could you review it and send me some extra inputs based on my progress?
@adityatr64

**Comment by adityatr64** [comment]
I shall review and let you

**Comment by adityatr64** [comment]
!extend 30

**Comment by adityatr64** [comment]
@PerepaMoorty 
You can continue to work , and make a new pr with changes as mentioned
The hiding works well and the button looks fine 
- The major part of the issue was the background image
- choose as u please and align the button as required

**Comment by adityatr64** [comment]
!extend 60

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @PerepaMoorty  100

**Comment by adityatr64** [comment]
!assign @PerepaMoorty 90

**Comment by adityatr64** [comment]
!assign @PerepaMoorty 90

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @PerepaMoorty 60

**Comment by adityatr64** [comment]
!assign @PerepaMoorty 60

**Comment by mahika34** [comment]
can i be assigned?

**Comment by adityatr64** [comment]
> can i be assigned?

Sorry but the issue is now closed
