### ISSUE TITLE
Settings option in menu

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#4]
Currently the settings file exists but no real way to change it in game  

- Add a setting option to menu 
- update settings file as the user updates it in game
- setup some basic resolutions for user choice

**Comment by mahika34** [comment]
can i be assigned?

**Comment by adityatr64** [comment]
!assign @mahika34 60

**Comment by adityatr64** [comment]
@mahika34 i can reassign you if you are still working on it

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @mahika34 30

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by adityatr64** [comment]
!assign @Git-Cat-21

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
The issue is mostly sloved needs review before i can assign
