### ISSUE TITLE
Paddle mechanic

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#5]
In the current version the paddle follows the mouse 

- Implement Keyboard controls for the paddle 
- Add a option in the settings to toggle between mouse or keyboard
- Add sounds to bricks breaking and paddle

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by tvs-tanmay** [comment]
Could I be assigned to this?

**Comment by adityatr64** [comment]
seems like you have been assigned else where please complete that assignment and return here

**Comment by Tarun600GK** [comment]
can i get assigned to this please

**Comment by adityatr64** [comment]
!assign @Tarun600GK 50

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 45

**Comment by BhavikaPradeep** [comment]
can i be assigned to this

**Comment by adityatr64** [comment]
!assign @BhavikaPradeep 90

**Comment by BhavikaPradeep** [comment]
i got the keyboard movements , i just need to Add a option in the settings to toggle between mouse or keyboard
can i get extra time?

**Comment by BhavikaPradeep** [comment]
i need to go for midnight performances please extend the time

**Comment by adityatr64** [comment]
!extend 60

**Comment by adityatr64** [comment]
@BhavikaPradeep Are you Still working on it ??

**Comment by adityatr64** [comment]
!deassign

**Comment by codespiderr** [comment]
Can you assign this please?

**Comment by BhavikaPradeep** [comment]
no pls reassign this to me i already finished half,please

**Comment by Roshr2211** [comment]
can you please assign it

**Comment by adityatr64** [comment]
!assign @Roshr2211 100

**Comment by adityatr64** [comment]
> no pls reassign this to me i already finished half,please

Im sorry but due to lack of reply and another person raising a co issue with it i have given it to a diffrent person

**Comment by BhavikaPradeep** [comment]
okay but could you please reassign it me after this cause i finished it, i couldnt reply earlier because of the performances

**Comment by codespiderr** [comment]
could you reassign it to me next?

**Comment by adityatr64** [comment]
> okay but could you please reassign it me after this cause i finished it, i couldnt reply earlier because of the performances

If the current person gives up i can queue yall up

**Comment by codespiderr** [comment]
any update about the next assignment?

**Comment by adityatr64** [comment]
he seems to be still working on it

> any update about the next assignment?

**Comment by codespiderr** [comment]
Is there a time limit?

**Comment by BhavikaPradeep** [comment]
100 mins ig

**Comment by codespiderr** [comment]
i'm ready with the push can I be assigned the task?

**Comment by adityatr64** [comment]
@Roshr2211 are u done with your pr? or ill have to assign someone else

**Comment by adityatr64** [comment]
> i'm ready with the push can I be assigned the task?

they will be given a few minutes to respond if they dont respond this issue will be reassigned

**Comment by codespiderr** [comment]
can I be assigned now?
