### ISSUE TITLE
The Paddle bounce back angle

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#6]
The angle and speed of the ball aren't affected by the hitting angle relative to the paddle

- The ball needs to calculate bounce back angle with respect to paddle rather than just stay on a single track or prefixed path
- The ball tends to change speed after hitting wall or paddle. keep it consistent

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
seems like you have been assigned else where please complete that assignment and return here

**Comment by Tarun600GK** [comment]
can i get assigned to this please

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 60

**Comment by adityatr64** [comment]
!assign @Tarun600GK 60

**Comment by adityatr64** [comment]
seems like you have been assigned else where please complete that assignment and return here

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 45

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 45

**Comment by adityatr64** [comment]
seems like you have been assigned else where please complete that assignment and return here

**Comment by aniruddhajoshi100** [comment]
I'm not assigned anywhere else

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 60

**Comment by bwaklog** [comment]
!assign @aniruddhajoshi100 60

**Comment by aniruddhajoshi100** [comment]
working on it, can I get more time

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
> working on it, can I get more time

yes yes

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 90

**Comment by BhavikaPradeep** [comment]
can i get assigned for this

**Comment by adityatr64** [comment]
There is already a person working on it

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 100

**Comment by BhavikaPradeep** [comment]
can i get assigned after him?

**Comment by adityatr64** [comment]
!deassign
