### ISSUE TITLE
Level up bug

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/breakout-remake#7]
The level doesn't increment after ends

- Start from level one
- change level if its cleared

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by tvs-tanmay** [comment]
Could I be assigned to this?

**Comment by adityatr64** [comment]
!assign @tvs-tanmay 30

**Comment by tvs-tanmay** [comment]
Could I be deassigned from this?

**Comment by adityatr64** [comment]
!deassign @tvs-tanmay

**Comment by aniruddhajoshi100** [comment]
can I get this assigned?

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 45

**Comment by aniruddhajoshi100** [comment]
working on it, can I have some more time

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @aniruddhajoshi100 60

**Comment by adityatr64** [comment]
!deassign
